build: off

os: unstable

environment:
  nodejs_version: '7'

cache:
  - node_modules -> package.json

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install -g npm
  - npm install
  - cd patch && npm install && cd ..

test_script:
  - node --version
  - npm --version
  - npm run lint
  - npm run build
  - npm test
